# Generated by Django 4.1.3 on 2022-11-15 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=80)),
                ('duration', models.FloatField()),
                ('explicit', models.BooleanField(default=False)),
                ('number_of_plays', models.BigIntegerField()),
                ('album', models.IntegerField()),
                ('genre', models.IntegerField()),
            ],
        ),
    ]
