# Generated by Django 4.1.3 on 2022-11-15 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0003_genre_tag_rename_artists_artist_rename_songs_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='grammies_won',
            field=models.SmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='song',
            name='number_of_plays',
            field=models.BigIntegerField(blank=True),
        ),
    ]
