# Generated by Django 4.1.3 on 2022-11-15 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0005_song_artists_alter_song_genre_playlist_album_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='name',
            field=models.CharField(default="Coder's Paradise", max_length=100),
        ),
        migrations.AddField(
            model_name='playlist',
            name='name',
            field=models.CharField(default='Living in the Source Code', max_length=100),
        ),
    ]
