# Generated by Django 4.1.3 on 2022-11-16 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0006_album_name_playlist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='duration',
            field=models.FloatField(default=210),
        ),
        migrations.AlterField(
            model_name='song',
            name='number_of_plays',
            field=models.BigIntegerField(),
        ),
    ]
