# Generated by Django 4.1.3 on 2022-11-17 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0009_remove_album_genre_album_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='artist',
        ),
    ]
