# Generated by Django 4.1.3 on 2022-11-17 15:22

from django.db import migrations, models
import songs.models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0010_remove_album_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='grammies_won',
            field=models.SmallIntegerField(blank=True, default=0, validators=[songs.models.validate_positive]),
        ),
    ]
