# Generated by Django 4.1.3 on 2022-11-17 15:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0012_alter_artist_bio_alter_artist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='grammies_won',
            field=models.SmallIntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
